apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-type-1
spec:
  selector:
    app: {{ .Chart.Name }}-deployment-type-1
  ports:
    - protocol: TCP
      port: {{ .Values.service.type1.servicePort }}
      targetPort: {{ .Values.deployments.type1.containerPort }}
  type: LoadBalancer
