apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-type-2
spec:
  selector:
    app: {{ .Chart.Name }}-deployment-type-1
  ports:
    - protocol: TCP
      port: {{ .Values.service.type2.servicePort }}
      targetPort: {{ .Values.deployments.type2.containerPort }}
  type: NodePort
