apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-type-2-{{ include "uniqueString" . }}
spec:
  replicas: {{ .Values.deployments.type2.replicaCount }}
  selector:
    matchLabels:
      app: deployment-type-2-{{ include "uniqueString" . }}
  template:
    metadata:
      labels:
        app: deployment-type-2-{{ include "uniqueString" . }}
    spec:
      containers:
        - name: busybox
          image: busybox
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
          ports:
            - containerPort: {{ .Values.deployments.type2.containerPort }}
          env:
            - name: Type
              value: "2"
          command:
            - "sh"
            - "-c"
            - |
                while true; do
                  {
                    BODY="Current time: $(date)\n\nEnvironment Variables:\n$(printenv)\n";
                    echo -ne "HTTP/1.1 200 OK\r\nContent-Length: $(echo -ne "$BODY" | wc -c)\r\n\r\n$BODY";
                  } | nc -l -p {{ .Values.deployments.type2.containerPort }};
                done
      restartPolicy: Always
