apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  selector:
    app: {{ .Chart.Name }}-service
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.serviceType }}
