basicDeploy:
  name: basic-deploy
  deploymentType1:
    name: deployment-type-1.basic-deploy
    containerPort: 8080
    replicaCount: 3
  serviceType1:
    name: svc-type-1-x-basic-deploy
    servicePort: 8081
    type: NodePort
  deploymentType2:
    name: deployment-type-2.basic-deploy
    containerPort: 8080
    replicaCount: 3
  serviceType2:
    name: svc-type-2-x-basic-deploy
    servicePort: 8082
    type: NodePort

kubevirt:
  name: kubevirt
  virtualMachine: 
    name: vm.kubevirt
  virtualMachineService:
    name: vm-service-x-kubevirt
    type: NodePort
  dataVolume:
    name: vm-dv.kubevirt
    storageClassName: nfs-standard
  dataVolumeExtra:
    name: vm-dv-extra
    storageClassName: nfs-standard
    pvc:
      name: vm-dv-extra-pvc.kubevirt
      namespace: default

ingress:
  name: ingress   
