{{- range $i, $val := .Values.dataVolume.storageClasses }}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-{{ $val }}
spec:
  source:
    registry:
      url: docker://docker.io/rrukmantiyo/kubevirt-images:ubuntu-22.04
  storage:
    storageClassName: {{ $val }}
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
---
{{ end -}}
