{{- range $i, $val := .Values.dataVolume.storageClasses }}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-{{ $val }}-{{ .Chart.Name }}-{{ .Release.Name }}
spec:
  source:
    registry:
      url: docker://docker.io/shakir31/kubevirt-images:UBUNTU_22.04
  storage:
    storageClassName: {{ $val }}
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
{{ end -}}
