apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-dv
spec:
  source:
    registry:
      url: docker://docker.io/rrukmantiyo/kubevirt-images:ubuntu-22.04
  storage:
    storageClassName: storage-nvme-c1 
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

