apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubevirt-dv-vm-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  {{- range $i, $val := .Values.dataVolume.storageClasses }}
    - host: {{ $val }}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-{{ $val }}
                port:
                  number: 80
  {{ end -}}  
