{{- range $i, $val := .Values.dataVolume.storageClasses }}
apiVersion: v1
kind: Secret
metadata:
  name: vm-{{ $val }}-user-credentials
type: Opaque
data:
  username: YWxpZnlhc2E=
  password: dWJ1bnR1
---
{{ end -}}