apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-vm
spec:
  running: false
  template:
    spec:
      domain:
        devices:
          disks:
            - name: dv-disk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 2Gi
      volumes:
        - name: dv-disk
          dataVolume:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-dv
