apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-vm
spec:
  running: false
  template:
    spec:
      domain:
        devices:
          disks:
            - name: dv-disk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
      volumes:
        - name: dv-disk
          dataVolume:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              #password: fedora
              #chpasswd: { expire: False }
              #cloud-config
              chpasswd:
              list: |
                ubuntu:QQ4j8fpusvqVgTu
                root:toor
              expire: False