{{- range $i, $val := .Values.dataVolume.storageClasses }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-{{ $val }}-{{ $.Chart.Name }}-{{ $.Release.Name }}
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
      volumes:
        - name: containerdisk
          dataVolume:
            name: dv-{{ $val }}-{{ $.Chart.Name }}-{{ $.Release.Name }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              #password: fedora
              #chpasswd: { expire: False }
              #cloud-config
              chpasswd:
              list: |
                ubuntu:QQ4j8fpusvqVgTu
                root:toor
              expire: False
---
{{ end -}}
