name: Package Helm Charts

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Find changed Helm charts
      id: find-charts
      run: |
        # Handle the case where HEAD~1 doesn't exist (e.g., on the first commit)
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD)
        else
          CHANGED_DIRS=$(git ls-files)
        fi

        echo "Changed directories: $CHANGED_DIRS" # Debug line

        # Get the list of Helm chart directories
        ALL_CHART_DIRS=$(find . -type d -name "charts" -or -name "templates" | xargs -I{} dirname {} | sort -u)

        echo "All chart directories: $ALL_CHART_DIRS" # Debug line

        # Initialize an empty variable to store directories of charts that have changed
        CHANGED_CHART_DIRS=""

        # Loop through all Helm chart directories and check if they are in the changed files list
        for CHART_DIR in $ALL_CHART_DIRS; do
          # Remove './' from CHART_DIR for comparison
          NORMALIZED_CHART_DIR=$(echo "$CHART_DIR" | sed 's|^\./||')

          if echo "$CHANGED_DIRS" | grep -q "$NORMALIZED_CHART_DIR"; then
            CHANGED_CHART_DIRS="$CHANGED_CHART_DIRS $CHART_DIR"
          fi
        done

        echo "Changed chart directories: $CHANGED_CHART_DIRS" # Debug line

        # Output the changed directories for the next step using environment files
        echo "changed-charts=$CHANGED_CHART_DIRS" >> $GITHUB_ENV

    - name: Package changed charts
      if: env.changed-charts != ''
      run: |
        echo "Packaging charts: ${{ env.changed-charts }}" # Debug line
        mkdir -p packaged-charts
        for CHART in ${{ env.changed-charts }}; do
          helm package "$CHART" --destination ./packaged-charts
        done

    - name: Upload Helm chart artifacts
      if: env.changed-charts != ''
      uses: actions/upload-artifact@v3
      with:
        name: helm-packaged-charts
        path: ./packaged-charts
