name: Package Helm Charts

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Find changed Helm charts
        run: |
          # Ensure we're on the right branch and fetch the history
          git fetch origin +refs/heads/main:refs/remotes/origin/main

          # Check for at least one commit in the repository
          if [ "$(git rev-list --count HEAD)" -le 1 ]; then
            echo "No previous commit found. Packaging all charts."
            # Get all chart directories for packaging
            CHANGED_DIRS=$(find . -name "Chart.yaml" -exec dirname {} \;)
          else
            # Get the list of changed files since the last commit
            CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD)
            echo "Changed directories: $CHANGED_DIRS" # Debug line

            # If no changes are detected, we can skip the rest
            if [[ -z "$CHANGED_DIRS" ]]; then
              echo "No changed directories detected."
              echo "changed-charts=" >> $GITHUB_ENV
              exit 0
            fi
          fi

          # Get the list of Helm chart directories
          ALL_CHART_DIRS=$(find . -type d -name "charts" -or -name "templates" | xargs -I{} dirname {} | sort -u)
          echo "All chart directories: $ALL_CHART_DIRS" # Debug line

          # Initialize an empty variable to store directories of charts that have changed
          CHANGED_CHART_DIRS=""

          # Loop through all Helm chart directories and check if they are in the changed files list
          for CHART_DIR in $ALL_CHART_DIRS; do
            # Remove './' from CHART_DIR for comparison
            NORMALIZED_CHART_DIR=$(echo "$CHART_DIR" | sed 's|^\./||')
            echo "Checking if '$NORMALIZED_CHART_DIR' is in changed directories..." # Debug line

            if echo "$CHANGED_DIRS" | grep -q "$NORMALIZED_CHART_DIR"; then
              CHANGED_CHART_DIRS="$CHANGED_CHART_DIRS $CHART_DIR"
              echo "Detected change in chart directory: $CHART_DIR" # Debug line
            fi
          done

          echo "Changed chart directories: $CHANGED_CHART_DIRS" # Debug line

          # Output the changed directories for the next step using environment files
          if [[ -n "$CHANGED_CHART_DIRS" ]]; then
            echo "changed-charts=$CHANGED_CHART_DIRS" >> $GITHUB_ENV
            echo "Changed charts set for next step: $CHANGED_CHART_DIRS" # Debug line
          else
            echo "changed-charts=" >> $GITHUB_ENV
            echo "No changed charts found." # Debug line
          fi

      - name: Upload Helm Chart Artifacts
        run: |
          # Check if there are changed charts
          if [[ -z "${{ env.changed-charts }}" ]]; then
            echo "No changed charts to upload."
            exit 0
          fi

          CHANGED_CHARTS=${{ env.changed-charts }}
          for CHART_DIR in $CHANGED_CHARTS; do
            # Navigate to the chart directory
            cd "$CHART_DIR" || exit 1
            
            # Package the chart
            helm package .
            
            # Find the .tgz file created and upload it
            ARTIFACT_NAME=$(basename "$CHART_DIR")
            echo "Uploading artifact for chart: $ARTIFACT_NAME"

            # Use v4 of the upload-artifact action
            echo "Upload $ARTIFACT_NAME.tgz"
            - name: Upload $ARTIFACT_NAME Artifact
              uses: actions/upload-artifact@v4
              with:
                name: $ARTIFACT_NAME
                path: "$ARTIFACT_NAME-*.tgz"  # Upload the packaged chart

            cd - || exit 1  # Return to the previous directory
          done
