name: Package Helm Charts

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Find changed Helm charts
      id: find-charts
      run: |
        # Get the list of changed files from the last commit
        CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD)

        # Get the list of Helm chart directories (assumed to be the parent directories of charts and templates folders)
        ALL_CHART_DIRS=$(find . -type d -name "charts" -or -name "templates" | xargs -I{} dirname {} | sort -u)

        # Initialize an empty variable to store directories of charts that have changed
        CHANGED_CHART_DIRS=""

        # Loop through all Helm chart directories and check if they are in the changed files list
        for CHART_DIR in $ALL_CHART_DIRS; do
          if echo "$CHANGED_DIRS" | grep -q "$CHART_DIR"; then
            CHANGED_CHART_DIRS="$CHANGED_CHART_DIRS $CHART_DIR"
          fi
        done

        # Output the changed directories for the next step
        echo "::set-output name=changed-charts::$CHANGED_CHART_DIRS"

    - name: Package changed charts
      if: steps.find-charts.outputs.changed-charts != ''
      run: |
        # Create a directory to store the packaged charts
        mkdir -p packaged-charts

        # Iterate over the changed charts and package them
        for CHART in ${{ steps.find-charts.outputs.changed-charts }}; do
          helm package "$CHART" --destination ./packaged-charts
        done

    - name: Upload Helm chart artifacts
      if: steps.find-charts.outputs.changed-charts != ''
      uses: actions/upload-artifact@v3
      with:
        name: helm-packaged-charts
        path: ./packaged-charts
