apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.jobs.monitorJob.name }}
spec:
  serviceAccountName: {{ .Values.jobs.monitorJob.serviceAccount.name }}
  containers:
    - name: bash-script-container
      image: bitnami/kubectl:latest
      command:
        - sh
        - -c
        - |
          # Run the monitor.sh script with arguments from values.yaml
          touch /tmp/script-output.txt 
          touch /tmp/script-error.txt
          whoami >> /tmp/script-output.txt 2>> /tmp/script-error.txt
          ls -la /scripts >> /tmp/script-output.txt 2>> /tmp/script-error.txt
          cat /scripts/monitor.sh >> /tmp/script-output.txt 2>> /tmp/script-error.txt
          
          mkdir -p /tmp/scripts/
          cp /scripts/monitor.sh /tmp/scripts/monitor.sh >> /tmp/script-output.txt 2>> /tmp/script-error.txt
          chmod +x /tmp/scripts/monitor.sh >> /tmp/script-output.txt 2>> /tmp/script-error.txt

          {{- range .Values.jobs.monitorJob.scripts }}
          {{- $resourceName := (index (splitList " " .) 1) }}
          /tmp/scripts/monitor.sh {{ . }} >> /tmp/script-output.txt 2>> /tmp/script-error.txt

          # Create a new ConfigMap YAML and replace the existing ConfigMap
          kubectl create configmap {{ $resourceName }}-{{ $.Values.jobs.monitorJob.script.resultConfigMapName }} \
            --from-file=output=/tmp/script-output.txt \
            --from-file=error=/tmp/script-error.txt \
            --dry-run=client -o yaml > /tmp/configmap.yaml
          kubectl replace -f /tmp/configmap.yaml
          {{- end }}
      volumeMounts:
        - name: script-volume
          mountPath: /scripts
  restartPolicy: Never
  volumes:
    - name: script-volume
      configMap:
        name: {{ .Values.data.scriptsConfigMap.name }}
        items:
          - key: monitor.sh
            path: monitor.sh
